[package]
name = "linked_lists"
version = "0.1.0"
authors = ["Ralph Crosby <rwc@cs.tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
